Added new filter effect shakeoscillate
dyne/frei0r pull request #201
Opened 2024-11-15 10:43 UTC by jaromil

rebase of PR #197 by @JohannJEG

2025-06-15 19:59 UTC, rrrapha requested changes

2025-06-15 19:59 UTC, rrrapha commented on src/filter/shakeoscillate/shakeoscillate.cpp
> +    void clearScreen(cairo_t* cr, int width, int height) {
Parameters `width` and `height` are unused in this function and can be removed.

2025-06-15 19:59 UTC, rrrapha commented on src/filter/shakeoscillate/shakeoscillate.cpp
> +    unsigned int width;
It is not necessary to declare `width` and `height` here, see frei0r.hpp.

2025-06-15 19:59 UTC, rrrapha commented on src/filter/shakeoscillate/shakeoscillate.cpp
> +        this->width = width;
`width` and `height` are already set in the parent constructor, no need to do this here.

2025-12-30 02:23 UTC, luzpaz commented
Thanks for working on this,

2026-01-07 01:10 UTC, shadowfax65 commented
Will this be made available soon?

2026-06-08 16:55 UTC, shadowfax65 commented
Any update about when this will be available?

2026-06-08 18:03 UTC, JohannJEG commented
I have reworked this in a clean branch with a squashed commit history to comply with Conventional Commits and improve reviewability. The updated implementation is available here: 

https://github.com/dyne/frei0r/pull/283

2026-08-17 20:22 UTC, jaromil commented
moving on #283

2026-08-17 20:22 UTC, closed without merging